config/routes.rb
Rails.application.routes.draw do
  root to: "pokemons#index"
  resources :pokemons, only: [:show] do
    resources :pokeballs, only: [:create]
  end
  resources :trainers, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :pokemon
  belongs_to :trainer
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs
  has_many :trainers, through: :pokeballs
  has_one_attached :photo
  # validations à faire si voulu
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokeballs
  has_many :pokemons, through: :pokeballs
  has_one_attached :photo

  # validations à faire si voulu
end
# on peut faire (dans la view)
# trainer.pokeballs
# trainer.pokemons

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @pokeball = Pokeball.new(pokeball_params)
    @pokeball.pokemon = @pokemon
    if @pokeball.save
      redirect_to trainer_path(@pokeball.trainer)
    else
      render "pokemons/show", status: :unprocessable_entity
      # render pokemon_path(@pokemon), status: :unprocessable_entity #ça marche aussi
    end
  end

  private
  def pokeball_params
    params.require(:pokeball).permit(:trainer_id, :location, :caught_on)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @pokeball = Pokeball.new
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/index.html.erb
<div class="container">
  <h1>Pokedex</h1>
  <%= link_to "< Trainers", trainers_path  %>
  <% @pokemons.each do |pokemon| %>
    <%= link_to pokemon do  %>
      <h3><%= pokemon.name %></h3>
      <%= cl_image_tag pokemon.photo.key, alt: pokemon.name %>
    <% end %>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<div class="container">
  <div class="d-flex justify-content-around">
    <div class="mx-5">
      <%= link_to "< Pokedex", root_path  %>
      <h2><%= @pokemon.name %></h2>
      <p><%= @pokemon.element_type %></p>
      <%= cl_image_tag @pokemon.photo.key, alt: @pokemon.name %>
    </div>
    <div>
      <%= simple_form_for [@pokemon, @pokeball] do |f| %>
        <%= f.association :trainer %>
        <%= f.input :location %>
        <%= f.input :caught_on, as: :date, html5: true %>
        <%= f.submit "Attrappe le pokemon", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/trainers/index.html.erb
<div class="container">
  <%= link_to "< Pokedex", root_path  %>
  <h1>Trainers</h1>
  <% @trainers.each do |trainer| %>
    <%= link_to trainer do  %>
      <h3><%= trainer.name %></h3>
      <%= cl_image_tag trainer.photo.key, alt: trainer.name %>
    <% end %>
  <% end %>
</div>

app/views/trainers/show.html.erb
<div class="container">
  <div class="d-flex justify-content-around">
    <div class="mx-5">
      <%= link_to "< Trainers", trainers_path  %>
      <h2><%= @trainer.name %></h2>
      <p>Âge: <%= @trainer.age %></p>
      <%= cl_image_tag @trainer.photo.key, alt: @trainer.name %>
      </div>
    <div class="">
      <% @trainer.pokemons.each do |pokemon| %>
        <h3><%= pokemon.name %></h3>
        <%= cl_image_tag pokemon.photo.key, alt: pokemon.name %>
      <% end %>
    </div>
  </div>
</div>